//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_hakkimizdaVERILER
    {
        public int VeriId { get; set; }
        public string DETAY1 { get; set; }
        public string DETAY2 { get; set; }
        public string DETAY3 { get; set; }
        public string DETAY4 { get; set; }
    }
}
