//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_saatlerKONTROL
    {
        public TBL_saatlerKONTROL()
        {
            this.TBL_Randevu = new HashSet<TBL_Randevu>();
        }
    
        public byte id { get; set; }
        public string saatler { get; set; }
        public Nullable<bool> SaatDurum { get; set; }
    
        public virtual ICollection<TBL_Randevu> TBL_Randevu { get; set; }
    }
}
