//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_iletisimMESAJ
    {
        public byte ID { get; set; }
        public string isim { get; set; }
        public string telNO { get; set; }
        public string eMail { get; set; }
        public string konu { get; set; }
        public string mesaj { get; set; }
        public Nullable<System.DateTime> zaman { get; set; }
    }
}
