//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Randevu
    {
        public int RandevuId { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public string MusteriTelNo { get; set; }
        public string MusteriMail { get; set; }
        public Nullable<byte> PersonelIdFK { get; set; }
        public Nullable<byte> KategoriIdFK { get; set; }
        public string Tarih { get; set; }
        public Nullable<byte> SaatIdFK { get; set; }
        public Nullable<short> Ucret { get; set; }
        public string Foto { get; set; }
        public Nullable<bool> FotoDurum { get; set; }
    
        public virtual TBL_calisanlarBILGI TBL_calisanlarBILGI { get; set; }
        public virtual TBL_Kategori TBL_Kategori { get; set; }
        public virtual TBL_saatlerKONTROL TBL_saatlerKONTROL { get; set; }
    }
}
